name: Run R Script in Docker
 
on:
  push:
    paths:
      - script.R
  workflow_dispatch:
 
jobs:
  run-r-docker:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Run R script inside Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            rocker/tidyverse:latest \
            Rscript script.R
